[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && npx tsx server.ts"
healthcheckPath = "/api/health-check"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
